package com.quota.api.request;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * 额度操作请求，包含申请、额度新增、额度扣减，后续也可以扩展到额度冻结之类的操作
 */
public class QuotaOperateRequest implements Serializable {

    private static final long serialVersionUID = -3689060344488874530L;

    /**
     * 用户id
     */
    private String clientId;

    /**
     * 额度类型
     * @see com.quota.api.enums.QuotaTypeEnum
     */
    private String quotaType;

    /**
     * 币种
     * @see com.quota.api.enums.CurrencyEnum
     */
    private String currency;

    /**
     * 操作类型
     * @see com.quota.api.enums.QuotaOperateTypeEnum
     */
    private String operateType;

    /**
     * 金额
     */
    private BigDecimal amount;

    /**
     * 备注
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quota_info.clientId
     *
     * @return the value of quota_info.clientId
     *
     * @mbg.generated
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quota_info.clientId
     *
     * @param clientId the value for quota_info.clientId
     *
     * @mbg.generated
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quota_info.quotaType
     *
     * @return the value of quota_info.quotaType
     *
     * @mbg.generated
     */
    public String getQuotaType() {
        return quotaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quota_info.quotaType
     *
     * @param quotaType the value for quota_info.quotaType
     *
     * @mbg.generated
     */
    public void setQuotaType(String quotaType) {
        this.quotaType = quotaType == null ? null : quotaType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quota_info.currency
     *
     * @return the value of quota_info.currency
     *
     * @mbg.generated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quota_info.currency
     *
     * @param currency the value for quota_info.currency
     *
     * @mbg.generated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    public String getOperateType() {
        return operateType;
    }

    public void setOperateType(String operateType) {
        this.operateType = operateType;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quota_info.amount
     *
     * @return the value of quota_info.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quota_info.amount
     *
     * @param amount the value for quota_info.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quota_info.remark
     *
     * @return the value of quota_info.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quota_info.remark
     *
     * @param remark the value for quota_info.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}
