package com.quota.dal.dao;

import com.quota.dal.pojo.QuotaFlowDO;

public interface QuotaFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_flow
     *
     * @mbg.generated
     */
    int insert(QuotaFlowDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quota_flow
     *
     * @mbg.generated
     */
    int insertSelective(QuotaFlowDO record);
}